[project]
name = "pos-dados-puc-rio-mvp-sprint-eng-dados"
version = "0.1.0"
description = "MVP de Sprint Eng Dados na Pos Ciência de Dados & Analytics na PUC Rio"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.37.4",
    "dotenv>=0.9.9",
]
